// ISO 3166-1 alpha-2 codes, used for the onboarding "Nazionalità" select and stored as-is
// in User.nationality (see cloud/DESIGN.md / server schema).
export const COUNTRIES: { code: string; name: string }[] = [
  { code: "IT", name: "Italia" },
  { code: "US", name: "Stati Uniti" },
  { code: "GB", name: "Regno Unito" },
  { code: "DE", name: "Germania" },
  { code: "FR", name: "Francia" },
  { code: "ES", name: "Spagna" },
  { code: "CH", name: "Svizzera" },
  { code: "AT", name: "Austria" },
  { code: "BE", name: "Belgio" },
  { code: "NL", name: "Paesi Bassi" },
  { code: "PT", name: "Portogallo" },
  { code: "IE", name: "Irlanda" },
  { code: "LU", name: "Lussemburgo" },
  { code: "MC", name: "Monaco" },
  { code: "SM", name: "San Marino" },
  { code: "VA", name: "Città del Vaticano" },
  { code: "MT", name: "Malta" },
  { code: "GR", name: "Grecia" },
  { code: "CY", name: "Cipro" },
  { code: "AL", name: "Albania" },
  { code: "AD", name: "Andorra" },
  { code: "BA", name: "Bosnia ed Erzegovina" },
  { code: "BG", name: "Bulgaria" },
  { code: "HR", name: "Croazia" },
  { code: "CZ", name: "Repubblica Ceca" },
  { code: "DK", name: "Danimarca" },
  { code: "EE", name: "Estonia" },
  { code: "FI", name: "Finlandia" },
  { code: "HU", name: "Ungheria" },
  { code: "IS", name: "Islanda" },
  { code: "LV", name: "Lettonia" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lituania" },
  { code: "MK", name: "Macedonia del Nord" },
  { code: "MD", name: "Moldavia" },
  { code: "ME", name: "Montenegro" },
  { code: "NO", name: "Norvegia" },
  { code: "PL", name: "Polonia" },
  { code: "RO", name: "Romania" },
  { code: "RS", name: "Serbia" },
  { code: "SK", name: "Slovacchia" },
  { code: "SI", name: "Slovenia" },
  { code: "SE", name: "Svezia" },
  { code: "UA", name: "Ucraina" },
  { code: "XK", name: "Kosovo" },
  { code: "RU", name: "Russia" },
  { code: "BY", name: "Bielorussia" },
  { code: "TR", name: "Turchia" },
  { code: "CA", name: "Canada" },
  { code: "MX", name: "Messico" },
  { code: "BR", name: "Brasile" },
  { code: "AR", name: "Argentina" },
  { code: "CL", name: "Cile" },
  { code: "CO", name: "Colombia" },
  { code: "PE", name: "Perù" },
  { code: "VE", name: "Venezuela" },
  { code: "UY", name: "Uruguay" },
  { code: "PY", name: "Paraguay" },
  { code: "BO", name: "Bolivia" },
  { code: "EC", name: "Ecuador" },
  { code: "CN", name: "Cina" },
  { code: "JP", name: "Giappone" },
  { code: "KR", name: "Corea del Sud" },
  { code: "KP", name: "Corea del Nord" },
  { code: "IN", name: "India" },
  { code: "PK", name: "Pakistan" },
  { code: "BD", name: "Bangladesh" },
  { code: "ID", name: "Indonesia" },
  { code: "MY", name: "Malesia" },
  { code: "SG", name: "Singapore" },
  { code: "TH", name: "Thailandia" },
  { code: "VN", name: "Vietnam" },
  { code: "PH", name: "Filippine" },
  { code: "TW", name: "Taiwan" },
  { code: "HK", name: "Hong Kong" },
  { code: "KH", name: "Cambogia" },
  { code: "LA", name: "Laos" },
  { code: "MM", name: "Myanmar" },
  { code: "NP", name: "Nepal" },
  { code: "LK", name: "Sri Lanka" },
  { code: "AU", name: "Australia" },
  { code: "NZ", name: "Nuova Zelanda" },
  { code: "ZA", name: "Sudafrica" },
  { code: "EG", name: "Egitto" },
  { code: "MA", name: "Marocco" },
  { code: "DZ", name: "Algeria" },
  { code: "TN", name: "Tunisia" },
  { code: "LY", name: "Libia" },
  { code: "NG", name: "Nigeria" },
  { code: "KE", name: "Kenya" },
  { code: "ET", name: "Etiopia" },
  { code: "GH", name: "Ghana" },
  { code: "SN", name: "Senegal" },
  { code: "CI", name: "Costa d'Avorio" },
  { code: "CM", name: "Camerun" },
  { code: "UG", name: "Uganda" },
  { code: "TZ", name: "Tanzania" },
  { code: "ZW", name: "Zimbabwe" },
  { code: "AO", name: "Angola" },
  { code: "MZ", name: "Mozambico" },
  { code: "IL", name: "Israele" },
  { code: "PS", name: "Palestina" },
  { code: "JO", name: "Giordania" },
  { code: "LB", name: "Libano" },
  { code: "SY", name: "Siria" },
  { code: "IQ", name: "Iraq" },
  { code: "IR", name: "Iran" },
  { code: "SA", name: "Arabia Saudita" },
  { code: "AE", name: "Emirati Arabi Uniti" },
  { code: "QA", name: "Qatar" },
  { code: "KW", name: "Kuwait" },
  { code: "BH", name: "Bahrein" },
  { code: "OM", name: "Oman" },
  { code: "YE", name: "Yemen" },
  { code: "AF", name: "Afghanistan" },
  { code: "KZ", name: "Kazakistan" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "GE", name: "Georgia" },
  { code: "AM", name: "Armenia" },
  { code: "AZ", name: "Azerbaigian" },
];
